projekt_kainos/projekt_kainos/Models/Capital.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;


namespace projekt_kainos.Models
{
    public class Capital
    {
        public int Id { get; set; }
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime Date { get; set; }
        public decimal Value { get; set; }
    }

    public class CapitalToRead
    {
        public string Id { get; set; }
        public string Date { get; set; }
        public string Value { get; set; }
    }

    public class CapitalWithDates
    {
        public int Id { get; set; }

        public List<Capital> Capitals { get; set; }
        
        public decimal percentage { get; set; }
        public List<Capital> Locate { get; set; }
    }

    public class CapitalDbContext : DbContext
    {
        public DbSet<Capital> Capitals { get; set; }

        
    }
}

projekt_kainos/projekt_kainos/Controllers/CapitalsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CsvHelper;
using CsvHelper.Configuration;
using projekt_kainos.Models;

namespace projekt_kainos.Controllers
{
    public class CapitalsController : Controller
    {
        private CapitalDbContext db = new CapitalDbContext();

        // GET: Capitals
        public async Task<ActionResult> Index()
        {
            var cap = await db.Capitals.ToListAsync();
            return View(cap);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpPost]
        public async Task<ActionResult> Index(HttpPostedFileBase file)
        {
            string path = null;
            List<Capital> capitals = new List<Capital>();
            try
            {
                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    path = Path.Combine(Server.MapPath("~/App_data/upload/"), fileName);
                    file.SaveAs(path);
                    var csv = new CsvReader(new StreamReader(path));
                    csv.Configuration.Delimiter = ",";
                    csv.Configuration.HasHeaderRecord = false;
                    var CapitalsList = csv.GetRecords<CapitalToRead>();

                    foreach (var capital in CapitalsList)
                    {
                        Capital capitalToDisplay = new Capital();

                        capitalToDisplay.Id = int.Parse(capital.Id);
                        capitalToDisplay.Date = DateTime.Parse(capital.Date);
                        capitalToDisplay.Value = decimal.Parse(capital.Value.Replace('.', ','));
                        Console.WriteLine(capitalToDisplay);
                        capitals.Add(capitalToDisplay);

                    }

                    db.Capitals.RemoveRange(db.Capitals);

                    await db.SaveChangesAsync();
                    db.Capitals.AddRange(capitals);

                    await db.SaveChangesAsync();
                }
            }
            catch (Exception e)
            {
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        
        public async Task<ActionResult> CuttedIndex(DateTime startDate, DateTime endDate)
        {
            var capitals = await db.Capitals.Where(c => c.Date >= startDate && c.Date <= endDate).ToListAsync();
            return View("Index",capitals);
        }
        
        public async Task<ActionResult> Compare()
        {
            return View();
        }
        [HttpPost]
        public  ActionResult Compare(DateTime startDate, DateTime endDate, decimal percentage)
        {
            List<Capital> locate = new List<Capital>();
            var capitals =  db.Capitals.Where(c => c.Date >= startDate && c.Date <= endDate).ToList();
            if (capitals.Count < 1 || capitals == null)
            {
                return RedirectToAction("Compare");
            }
            capitals = capitals.OrderBy(c => c.Date).ToList();
            locate.Add(capitals[0]);
            percentage = percentage / 100 / 365;
            int i = 0;
            for (var day = startDate.Date.AddDays(1); day.Date < endDate.Date; day = day.AddDays(1))
            {
                i++;
                Capital loc = new Capital();
                loc.Date = day;
                loc.Value = locate[i-1].Value + locate[i - 1].Value*percentage;
                locate.Add(loc);
            }
            locate = locate.OrderBy(c => c.Date).ToList();
            var model  = new CapitalWithDates();
            model.Locate = locate;
            model.Capitals = capitals;
            model.percentage = percentage;
            return View(model);
        }
    }
}

projekt_kainos/projekt_kainos/Views/Capitals/Compare.cshtml
@model projekt_kainos.Models.CapitalWithDates

@{
    ViewBag.Title = "Compare";
}
<script type="text/javascript">
    var model = @Html.Raw(Json.Encode(Model));
</script>


<div class="row" style="margin-top: 15px">
    @using (Html.BeginForm(null, null, FormMethod.Post))
    {

        <div class="col-md-4">
            <span>Start Date</span>
            <input type="date" class="datepicker form-control" name="startDate" id="startDate" value="2015-11-11"/>
        </div>
        <div class="col-md-4">
            <span>End Date</span>
            <input id="endDate" type="date" class="datepicker form-control" name="endDate" id="endDate" value="2016-01-01"/>
        </div>
        <div class="col-md-3">
            <span>Interest Rate</span>
            <input type="number" class="form-control" name="percentage" value="0">
        </div>
        <div class="col-md-1" style="margin-top: 20px">
            
            <input type="submit" class="btn btn-default" name="SubmitDate" value="Go"/>
        </div>

    }
</div>



<div id="myCompareChart"></div>

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="~/Scripts/Compare.js"></script>

}

projekt_kainos/projekt_kainos/Views/Capitals/Index.cshtml
@model IEnumerable<projekt_kainos.Models.Capital>
@using System.ServiceModel.Dispatcher

@{
    ViewBag.Title = "Fundusz";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    var model = @Html.Raw(Json.Encode(Model));
</script>

<body >
<div class="container">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-4 col-md-offset-5 row">

        </div>
    </div>
    <div class="row" style="margin-top: 15px">
        @using (Html.BeginForm("CuttedIndex", "Capitals", FormMethod.Post))
        {
            <div class="col-md-5">
                <span>Start Date</span>
                <input type="date" class="datepicker form-control" name="startDate" value="2015-11-11"/>
            </div>
            <div class="col-md-5">
                <span>End Date</span>
                <input id="endDate" type="date" class="datepicker form-control" name="endDate" value="2016-01-01" />
            </div>
            <div class="col-md-2" style="margin-top: 20px">
               
                <input type="submit" class="btn btn-default" name="SubmitDate" value="Go"/>
            </div>
        }
    </div>
</div>
<div class="row" style="height: 600px; margin-top: 20px">



    <div class="col-md-3" style="overflow: auto; height: 800px">
        <table class="table table-fixed" >
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Value)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Value)
                    </td>

                </tr>
            }

        </table>
    </div>
    <div class="col-md-9">
        <div id="myChart" data-model="@Model">

        </div>
    </div>
</div>

</body>

    <div class="row" style="visibility: hidden">
        @using (Html.BeginForm("Index", "Capitals", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            <fieldset>
                <div class="col-md-1" style="text-align: center;">
                    @Html.Label("Plik")
                </div>
                <div class="col-md-4">
                    <input type="file" class="input-group" name="file" />
                </div>
                <div class="col-md-1">
                    <input type="submit" class="btn btn-default" name="Send" />
                </div>
            </fieldset>
        }
    </div>


@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="~/Scripts/Index.js"></script>
    
}

projekt_kainos/projekt_kainos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/bootstrap-datetimepicker.css"/>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Capital", "Index", "Capitals", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Compare", "Compare", "Capitals")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
           
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datetime")
    
   
    @RenderSection("scripts", required: false)
</body>
</html>